### ISSUE TITLE
Images are not being imported with the html file

### ISSUE THREAD

**Issue by rsozdance** [lee88688/logseq-mhtml-view-plugin#1]
Hello,

During my testing of the plugin, I exported a web page that contained some CSS and images. However, when I imported the index.html file and opened it in the Logseq renderer using the mhtml/html plugin, the CSS and images did not show up. Upon checking the files, I realized that the images and CSS file were not being imported to the file storage in the assets of logseq. I am not sure how to import them with the main HTML file so that when I open the file in Logseq, the graphs and other things show up.

The exported HTML page that I want to import consists of the following files:
index.html
style.css
images (folder)

I am using the latest version of Logseq on a Mac.

it shows like this:
<img width="1176" alt="Screenshot 2024-01-11 at 10 26 04 PM" src="https://github.com/lee88688/logseq-mhtml-view-plugin/assets/6954487/616aa455-b7f6-491e-a617-811572dfedb1">

while the original page is like this:
<img width="1327" alt="Screenshot 202f4-01-11 at 10 28 33 PM" src="https://github.com/lee88688/logseq-mhtml-view-plugin/assets/6954487/bf0bec61-5bd3-42d7-9db3-bfec27477474">

**Comment by lee88688** [comment]
do notuse browser to save to html file, please save to mhtml instead. plugin only imports one file. if you want use html file, you can use [this](https://github.com/gildas-lormeau/SingleFile) which can pack all resouce into one html file.
