### ISSUE TITLE
分两次添加注释会在page文件夹中新建一个注释文档。新建的注释文档中没有页面属性。

### ISSUE THREAD

**Issue by UIyidu9322** [lee88688/logseq-mhtml-view-plugin#3]
![image](https://github.com/user-attachments/assets/1a4e4f35-dd07-449b-8c6b-7d68ae9795a0)
![image](https://github.com/user-attachments/assets/53d332c6-3859-476b-8690-86532fafda2a)

**Comment by lee88688** [comment]
详细描述一下呢？没太看明白

**Comment by UIyidu9322** [comment]
> 详细描述一下呢？没太看明白

文字描述了半天写不明白，我画了个草图，不知道表达清楚了没，谢谢大佬。[图片](https://viewer.diagrams.net/?tags=%7B%7D&lightbox=1&highlight=0000ff&edit=_blank&layers=1&nav=1&title=htmlview.drawio#R%3Cmxfile%3E%3Cdiagram%20name%3D%22%E7%AC%AC%201%20%E9%A1%B5%22%20id%3D%22WSxi276WGEXi1pPuaUhv%22%3E7V1Zs5s2FP4tfeDRd9gRj%2BAl6bTpZOZO2%2BSpowu6NrkYuVi%2BS399j4TALHJM4j1hJpOg7RhJn84uolnj5eu7HK8WH2hMUs3U41fNmmimafrIhH94zVtRYzjIKWrmeRLLum3FffIfkZW6rN0kMVk3OjJKU5asmpURzTISsUYdznP60uz2SNPmr67wXP6ivq24j3BKOt3%2BTmK2kLWG628b3pNkvpA%2FjUyvaFjisrMkvF7gmL7UqqypZo1zSlnxtHwdk5SvXrkuxbjZjtbqxXKSsT4D%2Fnn5833w4f7d%2Fcfwj9%2F%2Bepr8agSbkWEXZJ5xupEzlm%2FL3soleFkkjNyvcMTLL7DPmhUu2DKFkgGPOd1kMYllaf1EWLSQhQWOFpucvONDJjZUfEnmc0EWZh9Gm%2FyZzBLGkmxejmY5fSJjmtIcamLyiDcpTC7EaTLPoCaCuRJoCp9JzhLYpUA2LJM45oTDR5qxGV4mqQDc1NEAbwHSpq7mu1qoa1NPCwwtGIuHsebbvClwtNDTprYW%2BlrgiqaphnRJToLSKsvd13tM0lTx0nkkhxp86JI%2B4wcxeV7KyTr5r16mDLNaGQ4SqZdJnNSLKY2eqjWX2K81y02FRSKvO%2BFiVCCE40vokrD8DbrIASNf4laeXFsWX2qnQNdl5aJ2AryyJ5ZHb17R3qITHiRAvwGsTher211EfM%2F4Bvt8g0OHP%2FgTLRjwfCw8HwFULmqCynIUqLIVoHJPhSlDBSpYQUCOxZc7RPwP1ACikCGWEmko7IAK1oR1NjyjGVHtdn19ZZ8aAHdiQQXcLVpb22ubp0HPSXAxcpu4QF1YmJYCFtapYGGbCrnoiunGyTM8zsXMYUWBTaIpX6Qw5KiB9UM%2BXzkOGUsudiha%2BfIHWqCLB8SXX1KEN6wTbUOLxKCRyKJEi2A1JYtqQuAwhkVztqBzmuH0d0pXsvILYexNwgpvGG3CFbY4f%2FtUiile%2BFxvmbzWmyZvNaQem6%2FRTS6OxoIx0A5NxwrgL4AB%2F4t3WN%2FNKYXp41WyvovoUjREa9F19li8DDxOgjziJy1ivMUMYc4AuOLg9mKfa4bzshsSM49rpWJ%2F%2BaZ%2B%2FbAABsoJ7UKp5UqNGOdzwvZJzu7py0mKWfLcfJGjn6XyLfedJbHRfMdhfwMNjcWOjzkMuoeq38kZJP3FJH1l9pTqo6eQ9OY5Jb1t3S5nvTOdgbmem7mim2CuaJdRJDkp4qzza5x04JnXyjMd17k0z7RvjWcOrO8IrK%2B0wK%2Bb9ZVvqWZ9YJmF%2FM%2FA%2Bm6R9bnuxdVFldUyAObInnFPuznHuKHb%2Bz3jlQerjlXfPBlYvUFO37ic3i%2BUe9sjem9In0lQK2wUIMhFtKGFE7GhoRbYvCaYaeG4xIPzrRz3MBifmEM2xcExOJHhNDmRoZKazlmlpn9rjKjmZLHrPpaRfqdXTpfBz9JiYmIdPpI8AdhwojXh%2Bu2czeltblhXxtkctQmCTGFnAB544EeArcAE8iSzC91Bmbwe68OwvB6MVKXSnYyROsYu4%2FaEyQ4dIP1QQInxenFU8YtaUevLZzM4irB12xusf80lAp1hC%2FyZaEJamQN0O%2BL85xXJ3y19rb7St%2F8JOZP0tRR2hSKwPESPb04g23qLtSqdLGdlrYpMWZ4fNtF8kSgGEEOTIVHsxIlihtFyFF88U8ztOikGEXlbIvJ7QmRO39Qr97Iicsi9%2Bgmlp9XK3XdUhslZpafb9XcMXPLGueQBPE0O%2FUgToFgzqFvXA1yjhceC28phW0h2Kdktz7hr%2B3c28j3f8Q1kuZ7ZpFuw%2Bw5dAfVqfgdw4SFJ68dlrq596Swt9%2Baiv0Nm6yV1V7dvvOWyuqurDq4M%2BV0%2FAtf0Lu7QcXdGWBp2kJDOQTAEX648%2BKK0cc4afPGMDgCuXQy%2FJuxT7fmzkMiOLG1FMC%2BUErgmugfJfXbJ3TdWc2HJrQjMTE2%2BcXwTy4dBPF%2BveEbWxcWzKt5SmMoTEaae8eUE0YuMMgIDD0EpuV2ZaMPD3WK9EZK7FJZNsFF8uyxB0BaRnHHZuXa1u%2B4urcHV%2FXdDmdyp0VpsHXAf3TRWr2JPyvatg7Sg85AfhUzb%2B3qklyymz%2BP%2F1VJXWQMORytfYVg0xBM1v8lrvL0q75axMoenekrKnlhzj9NH9vaG%2FIEKGaczFXfvK8oW%2F0VkXp8Xu%2BQ9KXlkl%2BE8ptHiPJppzWY6%2F8rLkTLn2wkzviJ6p9LZjJN9U8ZV5Sa3tbgsDvinpDRVEPaYKtzPqyM1tOK%2BClMXaDUcqdKey7pD%2FdRmK13QasNzhz95v5%2B6uia%2Fx%2BN9LM90%2BRmzAf4D%2FL8b%2Fg66VfiXcSBFeHy9wtluXUoiQ2hThyNV4x8mbGholi41NNlQvAVvyWi%2BxGmt7RnnCYZ%2FQU%2FADM7bek%2B%2FCK92dXmRYOGNtpT6ekoYAH0E6xGJo9oeSfPVAmeSpFnU8SSnUQKMIZPUqumIFpbDgEegUVITXKUAsPhiY43UC83j5o9XtOB9H54SIMdpFibdSB6BRj%2BhxAkaijUUg2MS0RzOBM1GbJFETxlZy7dIsoQlu%2FrWtuWr%2FaKCHXT6PaYUs%2FYaxMl6leK3snuaQIOp%2F5IsVzRnOGM7FPdKva5030rl7eri4pKVVKbBRpruuKLAgT3jY6QREAhdG%2BiaDVXdh85Crw90Mby6AAEq%2FEz46Cs1vGNdcSNA10LjeCp%2FZf91Nf3iTCtMpq6J1tvaalbt5BqqLTt8okh%2Bciw0pdEFFiyPJKsMIVhjv7C%2BdL6HPZeH84Ve69O742Bu1bWFFD%2BQNMTR01xMrpXseUJjDBjsfge6Uo2wTnaN2bu5TzT9vCrrDi11rwvbk369vS5sz%2B0N6fN4tT3Vt5KHa8wHc6KR1WREl7%2FF7N1cTvdwi%2Fnit5i9vhnhnt%2F7hJyJsSmSxIdbzLcXxPN78NGzXmL2PCWwhjya68mjub4vsns9kqWHO8w%2FpkD%2Bbtnr95W93rXJXlUAZrjDfGk2ewTO2v6k4SmvMENx%2Bx8JFcGR7f%2FHZE3%2FBw%3D%3D%3C%2Fdiagram%3E%3C%2Fmxfile%3E)
![image](https://github.com/user-attachments/assets/0f061605-8b9c-416e-9cea-2f1c38658546)

**Comment by lee88688** [comment]
看样子是是创建了一个新的页面，感觉是插件创建了多个笔记页面？我感觉可能和导入的页面文件有点关系，可能是文件名什么东西触发了这个bug，不知道你那个导入的文件方便分享不，用来做测试复现一下bug，你也可以考虑重命名这个文件改成简单的名称，看看还会触发这个bug不。

**Comment by UIyidu9322** [comment]
随便一个html文件都可以。
可能的原因：第一次点击logseq中的名称后，默认建立的json文件名称就被改了。
![image](https://github.com/user-attachments/assets/1be1c5e7-6d18-4f64-9249-649314b7372f)

**Comment by UIyidu9322** [comment]
随便一个html文件都可以。
可能的原因：第一次点击logseq中的名称后，最开始默认建立的json文件名称就被改了。
![image](https://github.com/user-attachments/assets/0b82bbc7-fd02-4c7f-83c4-f4d297327067)
[2-快照.zip](https://github.com/user-attachments/files/17614763/2-.zip)

**Comment by lee88688** [comment]
更新一下版本就行了，1.0.3

**Comment by UIyidu9322** [comment]
非常感谢！
